# Required line
version: '3'

# services is kind of equivalent to container
services: 
  redis-server:
    image: 'redis'
  node-app:
    restart: on-failure
    build: .
    ports: 
      - "8081:8081"
